services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kizuna_ocr
      MYSQL_USER: kizuna
      MYSQL_PASSWORD: 202310
    volumes:
     - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app-network

  mysql-cli:
    image: mysql:8.0
    command: sh -c "mysql -hmysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  fastapi_app:
    build: ./backend
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "8001:8080"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
  
